#!/usr/bin/env bash
# a Bash script that will display information about subdomains.

all_subdomains=("www" "lb-01" "web-01" "web-02")

function default_call(){
	local domain="$1"
	for sub in "${all_subdomains[@]}"; do
		dig "$sub.$domain" | grep -A1 "ANSWER SECTION:" | awk -v subst="$sub"'NR == 2 \
		{printf"The subdomain %s is a %s record and points to %s\n", subst, $4, $5}'
	done
}

function specific_call(){
	local domain="$1"
	sub="$2"
	subst="$2"
	dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'FNR == 2 \
	{printf"The subdomain %s is a %s record and points to %s\n", subst, $4, $5}'
}

if [ "$#" -eq 1 ]; then
	default_call "$1"
elif [ "$#" -ge 2 ]; then
	specific_call "$1" "$2"
fi
