#!/usr/bin/env bash
# This Bash script transfers a file from client to a server

file=$1
ip_addr=$2
username=$3
ssh_pk=$4

if [ $# -le 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else	
	scp -o StrictHostKeyChecking=no -i $ssh_pk $file $username@$ip_addr:~/
