#!/usr/bin/env bash
# A bash script that installs nginx server on an ubuntu os
# Update package list
sudo apt-get update -y

# Install nginx
sudo apt-get install nginx -y

# Create "Hello World!" index file using tee
echo "Hello World!" | sudo tee /var/www/html/index.html

# Backup the default configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_backup

# Define new location rule for redirection
value="\\\tlocation = /redirect_me {\n\\t\treturn 301 https://alxafrica.com;\n\\t}\n"

# Add the new redirection rule to the default configuration
sudo sed -i "53i $value" /etc/nginx/sites-available/default

# Restart nginx to apply the changes
sudo service nginx restart
