#!/usr/bin/env bash

# Install nginx on web-01 with some simple configuration changes to the listen port and default server block
if ! dpkg -l | grep -q nginx; then
    sudo apt-get update
    sudo apt-get install -y nginx
fi
sudo service nginx start
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
echo "Hello World!" >/var/www/html/index.html

av="/etc/nginx/sites-available/default_backup"

# copy the content of default server to default_backup
if [ ! -e "$av" ]; then
    cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_backup
fi

# add location block whose match must be exactly "redirect_me"
location="location = /redirect_me {\n\treturn 301 https://www.alxafrica.com;\n}\n"

default_server="/etc/nginx/sites-enabled/default"

if [ -e "$default_server" ]; then
    sudo rm "$default_server"
fi

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo nginx -s reload

# Append the location block to the default configuration file
cat <<EOT >> /etc/nginx/sites-enabled/default
$location
EOT
