#!/usr/bin/env bash
# Install nginx on web-01 with some simple configuration changes to the listen port and default server block
if ! dpkg -l | grep -q nginx; then
    apt-get update
    apt-get install -y nginx
    sudo nginx -s start
    sudo nginx -s enable
fi

sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
echo "Hello World!" >/var/www/html/index.html
av="/etc/nginx/sites-available/default_backup"
#copy the content of default server  to default_backup
# if [ ! -e "$av" ]; then
#	cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_backup
#fi

#add location block whose match must be exactly "redirect_me"

location="\\\n\tlocation = /redirect_me {\n\t\t return 301 https://www.alxafrica.com;\n\t}\n"
default_server="/etc/nginx/sites-enabled/default"

if [ -e "$default_server" ]; then
	sudo rm $default_server
fi

sudo touch $default_server
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sed -i "53i $location" /etc/nginx/sites-enabled/default

sudo nginx -s reload
