#!/usr/bin/env bash
#working with bash signals
echo "$$" >/var/run/myscript.pid
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'sudo rm /var/run/myscript.pid ; kill $$' SIGQUIT
trap 'sudo rm /var/run/myscript.pid ; kill $$' SIGQTERM
while true;
do
	echo "To infinity and beyond"
	sleep 2
done
