#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and "Hi" 1 time.
declare -i num=1
while ((num < 21));
do
	case $num in
		4)
		echo "bad luck from China"
		;;
		8)
		echo "bad luck from Japan"
		;;
		17)
		echo "bad luck from Italy"
		;;
		*)
		echo $num
		;;
	esac
	((num++));
done
