#!/usr/bin/env bash
# a Bash script that configures the container to fit the some specifc requirements
if pgrep apache2 >/dev/null; then
	sudo pkill apache2
sudo chown -R nginx:nginx /etc/nginx
sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo service nginx restart
